services:
  # FRONTEND DEV SERVICE
  nxtchess-frontend-dev:
    image: nxtchess-frontend-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '5173'
    environment:
      VITE_DEBUG: 'true'
      VITE_API_URL: 'https://api.placeholder.com/api'
      VITE_APP_TITLE: 'nxtchess'
      VITE_APP_VERSION: '1.0.0'
    command: ['yarn', 'dev']

  # FRONTEND PROD SERVICE
  nxtchess-frontend-prod:
    image: nxtchess-frontend-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '80:80'
    environment:
      VITE_DEBUG: 'false'
      VITE_API_URL: 'https://api.placeholder.com/api'
      VITE_APP_TITLE: 'nxtchess'
      VITE_APP_VERSION: '1.0.0'

  # TODO: BACKEND SERVICE (Golang + Postgres)
