services:
  db:
    image: postgres:15
    container_name: chess_db
    environment:
      POSTGRES_DB: chess_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  redis:
    image: redis:7
    container_name: chess_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chess_backend
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - db
    env_file:
      - .env

volumes:
  db_data:
